name: mighty_fitness
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Basic
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  flutter_vector_icons: ^2.0.0

  #Network
  http: ^1.1.0
  connectivity_plus: ^4.0.2

  #State Management
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0

  #Storage
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^2.17.0
  firebase_analytics: ^10.5.1
  firebase_crashlytics: ^3.3.7
  firebase_auth: ^4.10.1

  #login
  google_sign_in: ^6.1.5
  the_apple_sign_in: ^1.1.1

  #one signal
  onesignal_flutter: ^5.0.3

  #Other
  fluttertoast: ^8.2.2
  country_code_picker: ^3.0.0
  infinite_listview: ^1.1.0
  pedometer: ^4.0.1
  html: ^0.15.4
  url_launcher: ^6.1.14
  photo_view: ^0.14.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  google_mobile_ads: ^3.1.0
  flutter_widget_from_html_core: ^0.10.6

  video_player: ^2.7.2
  flutter_tts: ^3.8.3
  chewie: ^1.7.1
  draggable_bottom_sheet: ^1.0.2
  timezone: ^0.9.2
  flutter_inappwebview: ^5.8.0

  chat_gpt_flutter: ^1.0.15
  share_plus: ^7.1.0
  speech_to_text: ^6.3.0
  flutter_time_picker_spinner: ^2.0.0
  flutter_bounce: ^1.1.0
  card_swiper: ^3.0.1

  #localizations
  flutter_localizations:
    sdk: flutter

  #chart
  syncfusion_flutter_charts: ^23.1.40
  path_provider: ^2.1.1

  #payment
  razorpay_flutter: ^1.3.5
  flutter_stripe: ^9.4.0
  flutter_paystack: ^1.0.7
  flutter_braintree: ^3.0.0
  flutterwave_standard: ^1.0.8
  flutter_paytabs_bridge: ^2.6.1
  paytm: ^3.0.1
  bambara_flutter: ^0.0.6
  my_fatoorah: ^3.3.0

dependency_overrides:
  intl: ^0.18.1
  #  http: ^0.13.1
  win32: ^3.0.0
  razorpay_flutter: 1.3.3
  package_info_plus: 4.0.2
  http: ^0.13.5

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
#  web:
#    generate: true
#    image_path: "path/to/image.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "path/to/image.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "path/to/image.png"
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/Flag/
